<?php

namespace AppBundle\Repository;

/**
 * PlaylistSongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistSongRepository extends \Doctrine\ORM\EntityRepository
{
}
