users:
    type: rest
    resource: '@AppBundle/Controller/UserController.php'
auth-tokens:
    type: rest
    resource: '@AppBundle/Controller/AuthTokenController.php'
song:
    type: rest
    resource: '@AppBundle/Controller/SongController.php'
playlist:
    type: rest
    resource: '@AppBundle/Controller/PlaylistController.php'
playlistsong:
    type: rest
    resource: '@AppBundle/Controller/PlaylistSongController.php'